// Generated by ReScript, PLEASE EDIT WITH CARE


var DOM;

var Doc;

var Elem;

var HtmlElem;

var InputElem;

var EvtTarget;

export {
  DOM ,
  Doc ,
  Elem ,
  HtmlElem ,
  InputElem ,
  EvtTarget ,
  
}
/* No side effect */
